labels:
  app: eslint-config-travix
  team: origami
  language: nodejs

stages:
  prepare:
    parallelStages:
      audit-acceptance:
        image: extensions/npm-audit:stable
        action: audit
        level: high
        dev-level: critical
        when: status == 'succeeded' && branch != 'master'

      audit:
        image: extensions/npm-audit:stable
        action: audit
        level: high
        dev-level: critical
        workspace: travix
        channels:
          - '#dynamicweb-audits'
        when: status == 'succeeded' && branch == 'master'

      install:
        image: travix/npm-agent:erbium-alpine
        commands:
          - npm ci

  lint-and-build:
    parallelStages:
      lint:
        image: travix/npm-agent:erbium-alpine
        commands:
          - npm run lint

      build:
        image: travix/npm-agent:erbium-alpine
        commands:
          - npm run build

  release:
    image: travix/npm-agent:erbium-alpine
    env:
      NPM_TOKEN: estafette.secret(zLzuU8X5xWRB_vm6.K6U64ManpNZ89nc6GGPI7b-fzy2R_Vuhs-veDE47S1ztm_JxJqRGuHznAbtoUat4q_UXhQ==)
      GH_TOKEN: estafette.secret(zorp40rJxlc5Ak9z.0e2vit1wbxDpFYuYFmNdVOYSTM83oneiVa8GYRIboTnVbTJ3kgmlxCO2dV_dUUndFBz76LAA8og=.0eyrvcBzcELgF_L1Hnp8UutyasUsiTerA5c1eRUg9HP3W297pUXalNPg_-aJIu-oL-XN8yFRbUU1SwWwh9yE0VPbeU0=)
      GIT_AUTHOR_NAME: 'travix-frontend-services'
      GIT_AUTHOR_EMAIL: 'frontend-services@travix.com'
      GIT_COMMITTER_NAME: 'travix-frontend-services'
      GIT_COMMITTER_EMAIL: 'frontend-services@travix.com'
    commands:
      - npx semantic-release
    when:
      status == 'succeeded' &&
      branch == 'master'

  slack-notify:
    image: extensions/slack-build-status:stable
    workspace: travix
    channels:
      - '#dynamicweb-builds'
    when: branch == 'master'
