builder:
  track: stable

labels:
  app: eslint-config-travix
  team: origami
  language: nodejs

stages:
  release:
    image: travix/npm-agent:latest
    env:
      NPM_TOKEN: estafette.secret(zLzuU8X5xWRB_vm6.K6U64ManpNZ89nc6GGPI7b-fzy2R_Vuhs-veDE47S1ztm_JxJqRGuHznAbtoUat4q_UXhQ==)
      GH_TOKEN: estafette.secret(qnT0Xj4IaUsYKb4c.wmhSyuv6-kvK0LuvAQAe3NovxitW1ORMBohzfiV5u9ZrCQvOix9FEshNiyiR8htQ070KeLli9Mo=)
      GIT_AUTHOR_NAME: 'travix-frontend-services'
      GIT_AUTHOR_EMAIL: 'frontend-services@travix.com'
      GIT_COMMITTER_NAME: 'travix-frontend-services'
      GIT_COMMITTER_EMAIL: 'frontend-services@travix.com'
    commands:
      - npm ci
      - npm run lint
      - npm run build
      - npx semantic-release
    when:
      status == 'succeeded' &&
      branch == 'master'

